server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      server:
        webflux:
          routes:
            - id: ms-catalogo
              uri: lb://ms-catalogo
              predicates:
                - Path=/categoria/**
            - id: ms-clientes
              uri: lb://ms-clientes
              predicates:
                - Path=/categoria/**