spring:
  application:
    name: ms-auth
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:123456@localhost:7071
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
jwt:
  secret: secret
